"""empty message

Revision ID: 98abd1904ecd
Revises: 60d6063d988a
Create Date: 2020-06-03 18:59:58.828758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98abd1904ecd'
down_revision = '60d6063d988a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Casts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['Actors.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['Movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Casts')
    # ### end Alembic commands ###
