"""empty message

Revision ID: c754c229467c
Revises: 98abd1904ecd
Create Date: 2020-06-05 11:30:22.463153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c754c229467c'
down_revision = '98abd1904ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Casts_movie_id_fkey', 'Casts', type_='foreignkey')
    op.drop_constraint('Casts_actor_id_fkey', 'Casts', type_='foreignkey')
    op.create_foreign_key(None, 'Casts', 'Actors', ['actor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Casts', 'Movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Casts', type_='foreignkey')
    op.drop_constraint(None, 'Casts', type_='foreignkey')
    op.create_foreign_key('Casts_actor_id_fkey', 'Casts', 'Actors', ['actor_id'], ['id'])
    op.create_foreign_key('Casts_movie_id_fkey', 'Casts', 'Movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###
